apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default
type: Opaque
stringData:
  # Sensitive data (Replace with actual secure values in production)
  JWT_SECRET: "your-secret-at-least-32-characters-long"
  MAIL_USERNAME: "your-email@gmail.com"
  MAIL_PASSWORD: "your-app-password"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  # Shared application configuration
  SPRING_DATA_MONGODB_URI: "mongodb://mongodb:27017/MaBase"
  SPRING_RABBITMQ_HOST: "rabbitmq"
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_RABBITMQ_USERNAME: "guest"
  SPRING_RABBITMQ_PASSWORD: "guest"
  JWT_EXPIRATION: "86400000"
  MAIL_FROM: "your-email@gmail.com"
